BcSecurity:
  Enabled: true

BcSecurity/LoggingRawPost:
  Description: Detect instances where `raw_post` is passed to Rails.logger.*
  Enabled: true

BcSecurity/LoggingObject:
  Description: Detect instances where object's string representation is passed to Rails.logger.*
  Enabled: true
